# GitHub Actions Workflow for Wisecow CI/CD
# This workflow automatically builds and pushes Docker image when code is pushed

name: Wisecow CI/CD Pipeline

# Trigger: Run this workflow when code is pushed to main branch
on:
  push:
    branches:
      - main

# Environment variables used throughout the workflow
env:
  DOCKER_IMAGE_NAME: wisecow
  DOCKER_TAG: latest

jobs:
  # Job 1: Build and Push Docker Image
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up Docker Buildx (for advanced Docker builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Step 3: Login to Docker Hub
    # Uses secrets stored in GitHub repository settings
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Step 4: Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
    
    # Step 5: Print success message
    - name: Image pushed successfully
      run: |
        echo "✅ Docker image pushed successfully!"
        echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}"

  # Job 2: Deploy to Kubernetes
  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push  # Wait for build job to complete
    
    steps:
    # Step 1: Checkout code to get Kubernetes manifests
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    # Step 3: Configure kubectl with kubeconfig
    - name: Configure kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
    
    # Step 4: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        echo "✅ Deployed to Kubernetes successfully!"
    
    # Step 5: Verify deployment
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/wisecow-deployment
        kubectl get pods -l app=wisecow
        kubectl get service wisecow-service
