# ============================================================================
# GitHub Actions CI/CD Workflow for Wisecow Application
# ============================================================================
# Author: Arpit Singh
# GitHub: @TSM-ArpitSG
# Purpose: Automate Docker image build, push to Docker Hub, and deployment
#          to Kubernetes Kind cluster for testing
# Triggers: On push to main branch
# Jobs: 1) Build & Push Docker Image  2) Deploy to Kind Kubernetes Cluster
# ============================================================================

# GitHub Actions Workflow for Wisecow CI/CD
# This workflow automatically builds and pushes Docker image when code is pushed

name: Wisecow CI/CD Pipeline

# Trigger: Run this workflow when code is pushed to main branch
on:
  push:
    branches:
      - main

# Environment variables used throughout the workflow
env:
  DOCKER_IMAGE_NAME: wisecow
  DOCKER_TAG: latest

jobs:
  # Job 1: Build and Push Docker Image
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from repository
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up Docker Buildx (for advanced Docker builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Step 3: Login to Docker Hub
    # Uses secrets stored in GitHub repository settings
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Step 4: Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
    
    # Step 5: Print success message
    - name: Image pushed successfully
      run: |
        echo "✅ Docker image pushed successfully!"
        echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}"

  # Job 2: Deploy to Kubernetes (using Kind cluster - 100% free!)
  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create Kind Cluster
      uses: helm/kind-action@v1.8.0
      with:
        cluster_name: wisecow-cluster
    
    - name: Verify cluster
      run: |
        kubectl cluster-info
        kubectl get nodes
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        echo "✅ Deployed to Kubernetes successfully!"
    
    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=ready pod -l app=wisecow --timeout=120s
    
    - name: Verify deployment
      run: |
        kubectl get deployment wisecow-deployment
        kubectl get pods -l app=wisecow
        kubectl get service wisecow-service
        echo "✅ Auto-deployment completed successfully!"